apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  namespace: default
  labels:
    app: synergychat-crawler
spec:
  selector:
    matchLabels:
      app: synergychat-crawler
  replicas: 1
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      containers:
        - image: bootdotdev/synergychat-crawler:latest
          name: synergychat-crawler
          envFrom:
            - configMapRef:
                name: synergychat-crawler-configmap
